name: Elisa's Duo Polski
# markdown: kramdown

# Google Analytics
google_analytics: G-7B0RJ4YE31

url: "https://elisa-duo-polski.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap