name: Polski Duo Notes
# markdown: kramdown

# Google Analytics
google_analytics: G-XTBEVLK1HL


url: "https://polski-duo-notes.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap